# This workflow will run tests and publish a package to npm on every push
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: sudo apt-get update && sudo apt-get install -y unixodbc-dev
      - run: npm ci
      - name: Run tests (if any)
        run: npm test || echo "No tests specified, continuing..."
        continue-on-error: true
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Configure npm authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{secrets.npm_token}}" > ~/.npmrc
      - run: sudo apt-get update && sudo apt-get install -y unixodbc-dev
      - name: Bump version for each commit
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          SHORT_SHA=$(git rev-parse --short HEAD)
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          # Use build metadata (after +) for timestamp and commit SHA
          # Format: existing-version+build.timestamp.sha (e.g., 1-beta.0+build.20241031183037.abc1234)
          # This preserves the existing version while adding unique build info
          NEW_VERSION="${CURRENT_VERSION}+build.${TIMESTAMP}.${SHORT_SHA}"
          npm pkg set version="${NEW_VERSION}"
      - run: npm install
      - run: npm publish --access public
